### PR TITLE
Add README; closes #2

### LINKED ISSUE #2: Add README

### PR DESCRIPTION
**Pull request by EmilyMB**
#### What does this PR do?
* Adds a README to this repo, since all good repos should have READMEs :smile:

### CODE REVIEW

**Comment by EmilyMB** [comment]
Is this what you had in mind, @kurenn?

**Comment by EmilyMB** [comment]
@kurenn @edolopez: We were talking with @lejandro83 and think that each person can write a section (without styling), but we need just one or two people to take all the sections and put them together into a beautiful html document. Thoughts?

**Comment by kurenn** [comment]
I think we can have it with markdown and keep using that format with middleman and buala!, what do you think?

**Comment by edolopez** [comment]
Yes, markdown would be enough per section or user commiting. I can be on
charge of reviewing the playbook in the end, though.
ᐧ

On Mon, Nov 9, 2015 at 1:04 AM, Abraham <notifications@github.com> wrote:

> I think we can have it with markdown and keep using that format with
> middleman and buala!, what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IcaliaLabs/playbook/pull/3#issuecomment-154972623>.
>



-- 
Eduardo

**Comment by lejandro83** [comment]
I added some changes to the readme branch. I think we need to save a Creative Friday as a company to build this playbook.

**Comment by edolopez** [comment]
Agree.
ᐧ

On Wed, Nov 11, 2015 at 5:08 PM, Alejandro <notifications@github.com> wrote:

> I added some changes to the readme branch. I think we need to save a
> Creative Friday as a company to build this playbook.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IcaliaLabs/playbook/pull/3#issuecomment-155938197>.
>



-- 
Eduardo

**Comment by EmilyMB** [comment]
Closing this PR since we went in a different direction.

**Pull request closed without merging**
